# Generated by Django 4.1.1 on 2022-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_create_incident_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_incident',
            name='incident_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
